#!/bin/bash

# --- IMPORTANT ---
# if you execute this file, your vimrc (if it exists) will be removed and replaced with the simple-vimrc

set -e

VIMRC=~/vimrc
if test -f "$VIMRC"; then
    echo "File .vimrc was found, so removing it."
    rm ~/.vimrc
fi

mv vimrc .vimrc
mv .vimrc ~

BASHRC=~/vimrc
if test -f "$BASHRC"; then
    echo "File .bashrc was found, so removing it."
    rm ~/.bashrc
fi

mv bashrc .bashrc
mv .bashrc ~

exit
