#!/bin/bash                                                                                                                  
                                                                                                                             
set -e                                                                                                                       
                                                                                                                             
FILE=~/.vimrc                                                                                                                
if test -f "$FILE"; then                                                                                                     
    rm .vimrc                                                                                                                
fi                                                                                                                           
                                                                                                                             
mv ~/simple-vimrc/.vimrc ~ 
