#!/bin/sh

# Stop execution if errors occur
set -e

# Install things
sudo apt update
sudo apt install vim nano ranger neovim -yy

# New .vimrc and .bashrc
if test -f "~/.vimrc"; then
        echo "This operation will remove your current .vimrc. Proceed? (y/N): "
        read inp1
        if [inp1="y"]; then
                rm ~/.vimrc
        fi
fi

if test -f "~/.bashrc"; then
        echo "This operation will remove your current .bashrc. Proceed? (y/N): "
        read inp2
        if [inp2="y"]; then
                rm ~/.bashrc
        fi
fi

cp vimrc init.vim
if [[ -d "/home/$USER/.config/nvim"]] || mkdir ~/.config/nvim
fi
mv init.vim ~/.config/nvim/
mv vimrc .vimrc
mv bashrc .bashrc
mv .vimrc ~
mv .bashrc ~

# Install plug-manager for neovim
sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

echo "Set up completed"
exit
