# /etc/keyd/default.conf
# Remapping of some keys to use 60% keyboard with physical US layout with IT layout.
# Keys like <>\| are not available physically on the keyboard for the IT layout, since it is a reduced keyboard.

[ids]
*

[main]
alt = layer(nav)

[nav]
h = left
k = up
j = down
l = right

[altgr]
dot = S-102nd
comma = 102nd
backslash = grave
| = S-grave
