# /etc/keyd/default.conf
# Remapping of some keys to use 60% keyboard with physical US layout with IT layout.
# Keys like <>\| are not available physically on the keyboard for the IT layout, since it is a reduced keyboard.


[ids]
*

[main]
alt = layer(nav)

# System key motions: Alt + h,k,j,l
[nav]
h = left
k = up
j = down
l = right

[altgr]
dot = S-102nd       # AltGr + >
comma = 102nd       # AltGr + < 
backslash = grave   # AltGr + \
| = S-grave         # AltGr + |
