fading = true;
fade-in-step  = 0.06;
fade-out-step = 0.06;
frame-opacity = 0.9;

corner-radius = 0

backend = "xrender"

dithered-present = false;

vsync = true;

detect-client-opacity = true;

use-damage = true;

transparent-clipping = false
rules: (
  {
    match = "class_g = 'Alacritty'";
    transparent-clipping = true;
  }
)
