return {
	"nvim-treesitter/nvim-treesitter",
	branch = "main",
	version = false,
	build = ":TSUpdate",
	opts = {
		indent = { enable = true },
		highlight = { enable = true },
		folds = { enable = true },
		auto_install = { enable = true },
		ensure_installed = {
			"bash",
			"c",
			"jsdoc",
			"json",
			"lua",
			"luadoc",
			"luap",
			"markdown",
			"markdown_inline",
			"printf",
			"toml",
			"vim",
			"vimdoc",
			"python",
			"rust",
			"cpp",
			"go",
			"cpp",
		},
	},
}
